name: Build and Push Release Images

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to GHCR
      run: |
        # Extract version from release tag or manual dispatch
        if [ "${{ github.event_name }}" = "release" ]; then
          TAG=${{ github.event.release.tag_name }}
        else
          TAG=${{ github.ref_name }}
        fi
        VERSION=${TAG#v}
        
        # Build and push with clean tags only - single platform to avoid SHA256 tags
        docker buildx build \
          --platform linux/amd64 \
          --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$VERSION \
          --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
          --provenance=false \
          --push \
          .
        
        echo "✅ Pushed ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$VERSION"
        echo "✅ Pushed ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
